### ISSUE TITLE
[Design] 마이 페이지 제작

### ISSUE THREAD

**Issue by minseo-hong** [Kusitms-28th-MeetUp-C/Client#12]
### Description  
마이 페이지 제작

### Todo  
- [x] 마이페이지 제작
- [x] 사이드바에 넣을 마이 페이지 링크 제작

### ETC  
- [x] 사이드 네비게이션 바에 애니메이션 추가
- [x] Overview 페이지에 애니메이션 추가
- [x] index.html 수정
