### ISSUE TITLE
[Design] 회의록 템플릿 제작

### ISSUE THREAD

**Issue by seungzzok** [Kusitms-28th-MeetUp-C/Client#16]
### Description  
회의록 템플릿 제작 및 레이아웃 수정

### Todo  
- [x] 회의록 템플릿 제작
- [x] 콘텐츠 내용만 스크롤 가능하도록 설정
- [x] 사이드바, 탑네비바 스타일 수정

### ETC  
추가 사항
