### ISSUE TITLE
[Design] 상단 네비게이션 바 제작

### ISSUE THREAD

**Issue by minseo-hong** [Kusitms-28th-MeetUp-C/Client#6]
### Description  
상단 네비게이션 바 제작

### Todo  
- [x] 상단 네비게이션 바 만들기
- [x] 사이드 네비게이션 바와 위치 맞추기
- [x] 레이아웃 컴포넌트 추가하기

### ETC  
레이아웃 컴포넌트 추가
